import { useMemo } from "react";
import dagre from "@dagrejs/dagre";
import { Background, Controls, ReactFlow, type Edge, type Node } from "@xyflow/react";
import "@xyflow/react/dist/style.css";
import type { DashboardTask } from "./types";

const text = (value: unknown) => value === null || value === undefined || value === "" ? "—" : String(value);
export function TaskGraph({ task }: { task: DashboardTask }) { const valid = task.tracking === "structured" && task.dag?.valid; const { nodes, edges } = useMemo(() => { const graph = new dagre.graphlib.Graph().setGraph({ rankdir: "LR", nodesep: 34, ranksep: 80 }).setDefaultEdgeLabel(() => ({})); (task.tasks ?? []).forEach((entry) => graph.setNode(entry.id, { width: 190, height: 74 })); (task.dag?.edges ?? []).forEach((edge) => graph.setEdge(edge.from, edge.to)); dagre.layout(graph); const nodes: Node[] = (task.tasks ?? []).map((entry) => { const pos = graph.node(entry.id) ?? { x: 0, y: 0 }; return { id: entry.id, position: { x: pos.x - 95, y: pos.y - 37 }, data: { label: <div><b>{entry.id}</b><br /><small>{text(entry.owner)} · {text(entry.status)} · {entry.ready ? "준비됨" : text(entry.blocked_reason)}</small></div> }, draggable: false, selectable: false }; }); const edges: Edge[] = (task.dag?.edges ?? []).map((edge) => ({ id: `${edge.from}-${edge.to}`, source: edge.from, target: edge.to, markerEnd: { type: "arrowclosed" } })); return { nodes, edges }; }, [task]); return <section><h3>Task DAG</h3>{valid ? <div className="graph" aria-label="방향성 task graph"><ReactFlow nodes={nodes} edges={edges} fitView nodesDraggable={false} nodesConnectable={false}><Background /><Controls showInteractive={false} /></ReactFlow></div> : <p className="notice">정상 graph를 표시할 수 없습니다. {task.dag?.diagnostics?.join(" · ") || "구조화된 DAG 기록이 없습니다."}</p>}<details open><summary>키보드용 dependency 관계</summary><ul>{(task.tasks ?? []).map((node) => <li key={node.id}><b>{node.id}</b> ({text(node.owner)}): {text(node.status)}, {node.ready ? "준비됨" : text(node.blocked_reason)}. 선행: {node.depends_on?.join(", ") || "없음"}</li>)}</ul></details></section>; }
export function AgentActivity({ task }: { task: DashboardTask }) {
  const agents = task.agents ?? [];
  const endpoints = agents.map((agent) => [Date.parse(agent.started_at ?? ""), Date.parse(agent.finished_at ?? "")] as const);
  const timeMode = endpoints.length > 0 && endpoints.every(([start, finish]) => Number.isFinite(start) && Number.isFinite(finish) && finish >= start);
  const min = timeMode ? Math.min(...endpoints.map(([start]) => start)) : 0;
  const max = timeMode ? Math.max(...endpoints.map(([, finish]) => finish)) : 1;
  return <section><h3>Agents</h3><p className="muted">{timeMode ? "기록된 시간축" : "기록된 wave / 순서 축"} · 지속 시간을 추정하지 않습니다.</p><div className={`lanes ${timeMode ? "time-lanes" : "wave-lanes"}`} aria-label={timeMode ? "기록된 agent 시간 관계" : "기록된 agent wave 관계"}>{agents.length ? agents.map((agent, index) => {
    const [start, finish] = endpoints[index];
    const left = timeMode ? ((start - min) / Math.max(max - min, 1)) * 100 : Math.min((Number(agent.wave) || index) * 18, 72);
    const width = timeMode ? Math.max(((finish - start) / Math.max(max - min, 1)) * 100, 4) : 22;
    return <div className="lane" key={`${agent.id}-${index}`}><b>{text(agent.id || agent.task_id)}</b><div className="lane-track" aria-hidden="true"><span className="lane-bar" style={{ left: `${left}%`, width: `${width}%` }} /></div><span>{text(agent.role)} · wave {text(agent.wave)} · {text(agent.status)}</span><small>{text(agent.requested_engine)} → {text(agent.effective_engine)} {agent.engine_fallback ? `· ${agent.engine_fallback}` : ""}</small><small>{timeMode ? `${text(agent.started_at)} → ${text(agent.finished_at)}` : `기록 순서 ${index + 1}`}</small></div>;
  }) : <p className="muted">구조화된 agent 기록이 없습니다.</p>}</div><details><summary>Agent text equivalent</summary><ul>{agents.map((agent, index) => <li key={`${agent.id}-text-${index}`}>{text(agent.id || agent.task_id)}: {text(agent.role)}, wave {text(agent.wave)}, {text(agent.status)}, {timeMode ? `${text(agent.started_at)} → ${text(agent.finished_at)}` : `기록 순서 ${index + 1}`}</li>)}</ul></details></section>;
}
export function CoordinationAndFanIn({ task }: { task: DashboardTask }) { const events = [...(task.events ?? [])].sort((a, b) => String(a.ts).localeCompare(String(b.ts))); const dispatches = task.dispatches ?? []; const integrations = task.integrations ?? []; const worktrees = task.worktrees ?? []; const waits = (task.tasks ?? []).filter((item) => item.ready === false && item.blocked_reason?.startsWith("dependency 대기:")); return <><section><h3>Coordination</h3><div className="dispatches">{dispatches.length ? dispatches.map((dispatch, index) => <div className="fan-in" key={`${dispatch.wave}-${index}`}><b>wave {text(dispatch.wave)}</b><span>tasks: {dispatch.task_ids?.join(", ") || "—"}</span><small>{text(dispatch.started_at)} → {text(dispatch.finished_at)}</small><small>{dispatch.fallback ? `기록된 fallback: ${dispatch.fallback}` : "기록된 fallback 없음"}</small></div>) : <p className="muted">기록된 dispatch wave가 없습니다.</p>}</div><div className="dependency-waits"><h4>Dependency waits</h4>{waits.length ? waits.map((item) => <p key={item.id}><b>{item.id}</b> · {item.blocked_reason}</p>) : <p className="muted">기록된 dependency 대기 없음</p>}</div><ol className="timeline">{events.length ? events.map((event, index) => <li key={`${event.ts}-${index}`}><time>{text(event.ts)}</time> · {text(event.event)} · task {text(event.task_id)} · wave {text(event.wave)} {event.evidence ? `· ${event.evidence}` : ""}</li>) : <li>기록된 coordination event가 없습니다.</li>}</ol></section><section><h3>Integrations</h3>{integrations.length ? integrations.map((integration, index) => { const result = integration.ok ? "fan-in 성공" : integration.failure_stage || integration.error || integration.status || "integration 결과 미확인"; return <div className="fan-in" key={`${integration.wave}-${index}`}><b>wave {text(integration.wave)}</b><span>tasks: {integration.task_ids?.join(", ") || "—"}</span><span>status {text(integration.status)} · result {result}</span><small>commit {text(integration.commit)} · fast-forward {String(integration.target_fast_forward ?? "—")} · {text(integration.cleanup)}</small></div>; }) : <p className="muted">integration 기록이 없습니다.</p>}</section><section><h3>Worktrees</h3>{worktrees.length ? worktrees.map((worktree, index) => <div className="fan-in" key={`${worktree.task_id}-${index}`}><b>{text(worktree.task_id)}</b><code>{text(worktree.path)}</code><button onClick={() => void navigator.clipboard?.writeText(worktree.path ?? "")}>경로 복사</button><span>base {text(worktree.base_commit)} · task {text(worktree.commit)}</span><small>{text(worktree.status)} · {text(worktree.cleanup)}</small></div>) : <p className="muted">writer worktree 기록이 없습니다.</p>}</section></>; }
export function CostView({ task }: { task: DashboardTask }) { const measurement = task.cost_measurement ?? "unknown"; const total = typeof task.total_cost_usd === "number" && Number.isFinite(task.total_cost_usd) ? task.total_cost_usd : null; const values = (task.iterations ?? []).map((item) => typeof item.cost === "number" && Number.isFinite(item.cost) ? item.cost : null).filter((item): item is number => item !== null); const max = Math.max(...values, total ?? 0, 1); return <section><h3>측정 비용</h3><p><b>{total === null || measurement === "unknown" || measurement === "unavailable" ? "측정 안 됨" : `$${total.toFixed(2)}`}</b> · {measurement === "full" ? "전체 측정" : measurement === "partial" ? "일부 측정" : measurement === "unavailable" ? "측정 불가" : "측정 상태 미확인"}</p>{values.length ? <svg className="cost" viewBox="0 0 240 72" role="img" aria-label={`반복별 측정 비용: ${values.map((value) => `$${value.toFixed(2)}`).join(", ")}`}><polyline points={values.map((value, index) => `${index * (220 / Math.max(values.length - 1, 1)) + 10},${62 - value / max * 50}`).join(" ")} fill="none" stroke="currentColor" strokeWidth="3" /></svg> : <p className="muted">반복별 측정값이 없습니다.</p>}<small>예산 상한은 기록된 경우에만 표시합니다.</small></section>; }
